version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
        
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.1
    depends_on:
      - elasticsearch

  webapia:
    image: ${DOCKER_REGISTRY-}webapia
    build:
      context: .
      dockerfile: WebApiA/Dockerfile
    depends_on:
      - webapib

  webapib:
    image: ${DOCKER_REGISTRY-}webapib
    build:
      context: .
      dockerfile: WebApiB/Dockerfile
    depends_on:
      - webapic

  webapic:
    image: ${DOCKER_REGISTRY-}webapic
    build:
      context: .
      dockerfile: WebApiC/Dockerfile
    
volumes: 
  elasticsearch-data-volume:
    driver: local

