version: '3.4'

services:
  webapia:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ElasticConnectionString=http://elasticsearch:9200
      - Urls__MyServiceUrl=http://webapib
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  webapib:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ElasticConnectionString=http://elasticsearch:9200
      - Urls__MyServiceUrl=http://webapic
    ports:
     - "5001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  webapic:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ElasticConnectionString=http://elasticsearch:9200
    ports:
      - "5002:80"

  elasticsearch:
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits: 
      memlock:
        soft: -1 
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: 
      - IPC_LOCK
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
        
  kibana:
    container_name: kibana
    restart: always
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"

    
volumes: 
  elasticsearch-data-volume:
    driver: local

