#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["WebApiA/WebApiA.csproj", "WebApiA/"]
COPY ["Logging/Logging.csproj", "Logging/"]
RUN dotnet restore "WebApiA/WebApiA.csproj"
COPY . .
WORKDIR "/src/WebApiA"
RUN dotnet build "WebApiA.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebApiA.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApiA.dll"]